name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Prisma Generate
        run: npm run db:generate

      - name: Display Node and npm versions and list dependencies
        run: |
          node -v
          npm -v
          npm ls lightningcss  # Check if lightningcss and its binaries are installed correctly

      - name: Run Build
        run: npm run build
